apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: test-app
    appstudio.openshift.io/component: hacbs-test-project-ccqc
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: hacbs-test-project-ccqc
  namespace: psturc-tenant
spec:
  url: https://github.com/psturc-org/hacbs-test-project
