apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ccqc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ccqc
    app.kubernetes.io/part-of: test-app
  name: hacbs-test-project-ccqc
  namespace: psturc-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: hacbs-test-project-ccqc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: hacbs-test-project-ccqc
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:psturc-tenant-hacbs-test-project-ccqc
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
