apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ccqc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ccqc
    app.kubernetes.io/part-of: test-app
  name: hacbs-test-project-ccqc
  namespace: psturc-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: hacbs-test-project-ccqc
status:
  loadBalancer: {}
